name: Sub-Issue Management

on:
  issues:
    types: [opened, edited]

jobs:
  check_parent_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Check for parent issue and add labels
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const issueNumber = issue.number;

            try {
              // GraphQLクエリを実行して親Issueの情報を取得
              const query = `
                query($owner: String!, $repo: String!, $issueNumber: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $issueNumber) {
                      id
                      number
                      title
                      parent {
                        id
                      }
                    }
                  }
                }
              `;
              
              const variables = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issueNumber: issueNumber
              };
              
              const result = await github.graphql(query, variables);
              console.log(`Issue data: ${JSON.stringify(result)}`);
              
              // 親Issueが存在するかチェック
              const hasParent = result.repository.issue.parent !== null;
              
              if (hasParent) {
                console.log(`Issue #${issueNumber} has a parent issue. Adding subissue label.`);
                
                // 現在のラベルを取得
                const labels = issue.labels.map(label => label.name);
                const hasSubissueLabel = labels.includes('subissue');
                
                // subissueラベルが存在しない場合、追加
                if (!hasSubissueLabel) {
                  try {
                    await github.rest.issues.addLabels({
                      issue_number: issueNumber,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      labels: ['subissue']
                    });
                    console.log(`Added 'subissue' label to issue #${issueNumber}`);
                  } catch (labelError) {
                    console.error(`Error adding label: ${labelError.message}`);
                    // ラベルがリポジトリに存在するか確認
                    console.log("Make sure the 'subissue' label exists in your repository");
                  }
                }
                
                console.log(`Issue #${issueNumber} has been processed as a sub-issue`);
              } else {
                console.log(`Issue #${issueNumber} does not have a parent issue.`);
              }
            } catch (error) {
              console.error(`Error processing issue: ${error.message}`);
            }

      - name: Add issue to project
        if: success()
        uses: actions/github-script@v7
        with:
          # PAT（Personal Access Token）を使用してプロジェクトの操作を行う
          github-token: ${{secrets.PROJECT_ACCESS_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const issueNumber = issue.number;

            try {
              // GraphQLクエリを実行して親Issueの情報を取得
              const query = `
                query($owner: String!, $repo: String!, $issueNumber: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $issueNumber) {
                      id
                      number
                      title
                      parent {
                        id
                      }
                    }
                  }
                }
              `;
              
              const variables = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issueNumber: issueNumber
              };
              
              const result = await github.graphql(query, variables);
              
              // 親Issueが存在するかチェック
              const hasParent = result.repository.issue.parent !== null;
              
              if (hasParent) {
                // 指定されたGitHub Projectに追加
                try {
                  // Project項目のIDを取得するGraphQLクエリ
                  const projectQuery = `
                    query {
                      user(login: "tHasegawa13") {
                        projectV2(number: 1) {
                          id
                        }
                      }
                    }
                  `;
                  
                  const projectData = await github.graphql(projectQuery);
                  const projectId = projectData.user.projectV2.id;
                  
                  // IssueをProjectに追加するためのGraphQLミューテーション
                  const addToProjectMutation = `
                    mutation($projectId: ID!, $contentId: ID!) {
                      addProjectV2ItemById(input: {
                        projectId: $projectId
                        contentId: $contentId
                      }) {
                        item {
                          id
                        }
                      }
                    }
                  `;
                  
                  await github.graphql(addToProjectMutation, {
                    projectId: projectId,
                    contentId: result.repository.issue.id
                  });
                  
                  console.log(`Added issue #${issueNumber} to project users/tHasegawa13/projects/1`);
                } catch (projectError) {
                  console.error(`Error adding issue to project: ${projectError.message}`);
                }
              }
            } catch (error) {
              console.error(`Error in project step: ${error.message}`);
            }
