name: List Epic Issues

on:
  workflow_dispatch: # 手動実行用

jobs:
  list-epic-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Epic Issues
        id: get-epic-issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = 'tHasegawa13';
            const repo = 'github_project_test';

            // Epicラベルを持つIssueを取得
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'Epic'
            });

            console.log('Epic Issues:');
            if (issues.data.length === 0) {
              console.log('No Epic issues found.');
            } else {
              issues.data.forEach(issue => {
                console.log(`#${issue.number} - ${issue.title}`);
              });
            }

            // 出力用に情報を設定
            const issueNumbers = issues.data.map(issue => issue.number);
            core.setOutput('epic_issues', issueNumbers);

            return {
              issueCount: issues.data.length,
              issueNumbers: issueNumbers
            };

      - name: Output Issue Count
        run: echo "Found ${{ fromJSON(steps.get-epic-issues.outputs.result).issueCount }} Epic issues"
